export enum EErrors {
    AUTH_EMAIL_PASSWORD_ERROR = 'AUTH_EMAIL_PASSWORD_ERROR',
    AUTH_2FA_ERROR = 'AUTH_2FA_ERROR',

    QUEUE_REQUIRED = 'QUEUE_REQUIRED',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',

    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    EMAIL_UNIQUE = 'EMAIL_UNIQUE',
    EMAIL_INVALID = 'EMAIL_INVALID',
    SMS_POST_ERROR = 'SMS_POST_ERROR',
    CODE_REQUIRED = 'CODE_REQUIRED',

    CREDIT_CARD_REQUIRED = 'CREDIT_CARD_REQUIRED',
    AMOUNT_REQUIRED = 'AMOUNT_REQUIRED',

    NO_COURSE_RECORD = 'NO_COURSE_RECORD',

    PRIOTRY_REQUIRED = 'PRIOTRY_REQUIRED',

    TITLE_REQUIRED = 'TITLE_REQUIRED',
    MESSAGE_REQUIRED = 'MESSAGE_REQUIRED',

    PROCESS_DATE_REQUIRED = 'PROCESS_DATE_REQUIRED',
    PROCESS_REQUIRED = 'PROCESS_REQUIRED',
    PROCESS_TYPE_REQUIRED = 'PROCESS_TYPE_REQUIRED',

    NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED',
    OLD_PASSWORD_AGAIN_REQUIRED = 'OLD_PASSWORD_AGAIN_REQUIRED',
    OLD_PASSWORD_REQUIRED = 'OLD_PASSWORD_REQUIRED',
    OLD_AND_NEW_DOESNT_MATCH = 'OLD_AND_NEW_DOESNT_MATCH',

    SIPAY_SERVER_ERROR = 'SIPAY_SERVER_ERROR', 

    COURSE_REQUIRED = 'COURSE_REQUIRED',
    ATTENDANCE_DATE_REQUIRED = 'ATTENDANCE_DATE_REQUIRED',
    
    DAY_REQUIRED = 'DAY_REQUIRED',
    LESSON_REQUIRED = 'LESSON_REQUIRED',

    ONSALE_REQUIRED = 'ONSALE_REQUIRED',
    COURSETYPE_REQUIRED = 'COURSETYPE_REQUIRED',
    TRAINER_REQUIRED = 'TRAINER_REQUIRED',
    CAPACITY_REQUIRED = 'CAPACITY_REQUIRED',
    DANCE_LEVEL_REQUIRED = 'DANCE_LEVEL_REQUIRED',
    DANCE_TYPE_REQUIRED = 'DANCE_TYPE_REQUIRED',

    END_DATE_REQUIRED = 'END_DATE_REQUIRED',
    START_DATE_REQUIRED = 'START_DATE_REQUIRED',

    END_TIME_REQUIRED = 'END_TIME_REQUIRED',
    START_TIME_REQUIRED = 'START_TIME_REQUIRED',

    PRICE_REQUIRED = 'PRICE_REQUIRED',

    IDENTITY_REQUIRED = 'IDENTITY_REQUIRED',

    CREDIT_REQUIRED = 'CREDIT_REQUIRED',

    SELLBY_REQUIRED = 'SELLBY_REQUIRED',

    ID_REQUIRED = 'ID_REQUIRED',

    STUDENT_REQUIRED = 'STUDENT_REQUIRED',

    IMAGE_REQUIRED = 'IMAGE_REQUIRED',
    DESCRIPTION_REQUIRED = 'DESCRIPTION_REQUIRED',

    ID_MUST_NUMBER = 'ID_MUST_NUMBER',
    
    PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
    PASSWORD_MIN = 'PASSWORD_MIN',

    NAME_LENGTH = 'NAME_LENGTH',

    TIME_REQUIRED = 'TIME_REQUIRED',
    
    TYPE_REQUIRED = 'TYPE_REQUIRED',
    STUDENT_OR_COURSE_REQUIRED = 'STUDENT_OR_COURSE_REQUIRED',
    
    REFEREDID_REQUIRED = 'REFEREDID_REQUIRED',

    NAME_REQUIRED = 'NAME_REQUIRED',
    NAME_MAX = 'NAME_MAX',
    
    STATUS_REQUIRED = 'STATUS_REQUIRED',

    ROLE_REQUIRED = 'ROLE_REQUIRED',

    PHONE_REQUIRED = 'PHONE_REQUIRED',
    PHONE_UNIQUE = 'PHONE_UNIQUE',
    PHONE_INVALID = 'PHONE_INVALID',

    HAVENT_RECORD = 'HAVENT_RECORD',

    BAD_REQUEST = 'BAD_REQUEST',

    PACKAGE_ID_REQUIRED = 'PACKAGE_ID_REQUIRED',

    CARD_OWNER_REQUIRED = 'CARD_OWNER_REQUIRED',
    CARD_NUMBER_REQUIRED = 'CARD_NUMBER_REQUIRED',
    EXPIRATION_DATE_REQUIRED = 'EXPIRATION_DATE_REQUIRED',
    CVV_REQUIRED = 'CVV_REQUIRED',
    INSTALLMENT_REQUIRED = 'INSTALLMENT_REQUIRED',
    DATE_REQUIRED = 'DATE_REQUIRED',
    HAVENT_CREDIT = 'HAVENT_CREDIT',
    QR_REQUIRED = 'QR_REQUIRED'
}
