export enum EErrors {
    AUTH_EMAIL_PASSWORD_ERROR = 'AUTH_EMAIL_PASSWORD_ERROR',
    AUTH_2FA_ERROR = 'AUTH_2FA_ERROR',

    QUEUE_REQUIRED = 'QUEUE_REQUIRED',

    EMAIL_REQUIRED = 'EMAIL_REQUIRED',
    EMAIL_UNIQUE = 'EMAIL_UNIQUE',
    EMAIL_INVALID = 'EMAIL_INVALID',

    PRICE_REQUIRED = 'PRICE_REQUIRED',

    IDENTITY_REQUIRED = 'IDENTITY_REQUIRED',

    CREDIT_REQUIRED = 'CREDIT_REQUIRED',

    ID_REQUIRED = 'ID_REQUIRED',

    IMAGE_REQUIRED = 'IMAGE_REQUIRED',
    DESCRIPTION_REQUIRED = 'DESCRIPTION_REQUIRED',

    ID_MUST_NUMBER = 'ID_MUST_NUMBER',
    
    PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',
    PASSWORD_MIN = 'PASSWORD_MIN',

    NAME_LENGTH = 'NAME_LENGTH',

    TIME_REQUIRED = 'TIME_REQUIRED',
    
    TYPE_REQUIRED = 'TYPE_REQUIRED',
    
    REFEREDID_REQUIRED = 'REFEREDID_REQUIRED',

    NAME_REQUIRED = 'NAME_REQUIRED',
    NAME_MAX = 'NAME_MAX',
    
    STATUS_REQUIRED = 'STATUS_REQUIRED',

    ROLE_REQUIRED = 'ROLE_REQUIRED',

    PHONE_REQUIRED = 'PHONE_REQUIRED',
    PHONE_UNIQUE = 'PHONE_UNIQUE',
    PHONE_INVALID = 'PHONE_INVALID',

    HAVENT_RECORD = 'HAVENT_RECORD',

    BAD_REQUEST = 'BAD_REQUEST',
}
